version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands: 
        - 'echo "--------INSTALL PHASE--------"'
        - 'npm i -g aws-cdk@2.21.1'
        - 'npm i'
  build:
    commands:
        - 'echo "--------BUILD PHASE--------"'
        - "cdk synth '*' "
artifacts:
    base-directory: cdk.out
    files: 
        - '**/*'